In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('C:/Users/Prajwal Amin/Desktop/MCA/3RD SEM/AI & ML/LAB/MyData.csv')
x1 = data['X1'].tolist()
x1

[30, 45, 68, 46, 66, 36]

In [3]:
x2=data['X2'].tolist()
x2

[63, 47, 67, 83, 84, 50]

In [4]:
x3 = data['X3'].tolist()
x3

[33, 52, 62, 42, 42, 66]

In [5]:
y=data['Y'].tolist()
y

[43, 63, 71, 61, 81, 43]

In [17]:
x = [1]*len(x1)

In [18]:
x=np.transpose([x,x1,x2,x3])
print(x)

[[ 1 30 63 33]
 [ 1 45 47 52]
 [ 1 68 67 62]
 [ 1 46 83 42]
 [ 1 66 84 42]
 [ 1 36 50 66]]


In [19]:
xt=np.transpose(xt)
xt


array([[ 1,  1,  1,  1,  1,  1],
       [30, 45, 68, 46, 66, 36],
       [63, 47, 67, 83, 84, 50],
       [33, 52, 62, 42, 42, 66]])

In [20]:
xtx=np.dot(xt,x)
xtx

array([[    6,   291,   394,   297],
       [  291, 15317, 19723, 14626],
       [  394, 19723, 27112, 18991],
       [  297, 14626, 18991, 15521]])

In [21]:
xtxi=np.linalg.inv(xtx)
xtxi

array([[ 1.69580230e+01,  8.31914459e-02, -1.73130574e-01,
        -1.91055228e-01],
       [ 8.31914459e-02,  1.89410821e-03, -1.54994977e-03,
        -1.48031635e-03],
       [-1.73130574e-01, -1.54994977e-03,  2.35593088e-03,
         1.89084867e-03],
       [-1.91055228e-01, -1.48031635e-03,  1.89084867e-03,
         2.80171396e-03]])

In [22]:
xty=np.dot(xt,y)
xty

array([  362, 18653, 24444, 17899])

In [23]:
bh=np.dot(xtxi,xty)
bh

array([38.8730967 ,  1.06294938, -0.15180574, -0.40655013])

In [24]:
v1=int(input())
v2=int(input())
v3=int(input())
ans=bh[0]+v1*bh[1]+v2*bh[2]+v3*bh[3]
ans

50
70
80


48.87015369722906