In [1]:

import numpy as np
import pandas as pd

s1=[1,0]
s2=[3,1]
s3=[3,-1]
s1.append(1)
s2.append(1)
s3.append(1)
print(s1)
s1t=np.transpose(s1)
s2t=np.transpose(s2)
s3t=np.transpose(s3)
print(s1t)
print(s2t)
print(s3t)
s1ts1=np.dot(s1t,s1)           
s1ts2=np.dot(s1t,s2)
s1ts3=np.dot(s1t,s3)
s2ts1=np.dot(s2t,s1)
s2ts2=np.dot(s2t,s2)
s2ts3=np.dot(s2t,s3)
s3ts1=np.dot(s3t,s1)
s3ts2=np.dot(s3t,s2)
s3ts3=np.dot(s3t,s3)
x=np.array([[s1ts1,s1ts2,s1ts3],[s2ts1,s2ts2,s2ts3],[s3ts1,s3ts2,s3ts3]])
print(x)
xt=np.transpose(x)
print(xt)
xtx=np.dot(xt,x)
print(xtx)
xtxi=np.linalg.inv(xtx)
print(xtxi)
y=np.array([-1,1,1])
xty=np.dot(xt,y)
print(xty)
bhat=np.dot(xtxi,xty)
print(bhat)
w=np.array([])
w=bhat[0]*s1t+bhat[1]*s2t+bhat[2]*s3t
print(w)
w=np.array([1,0])
p=np.array([4,2])
res=np.dot(w,p)
print(res)
                                                          



[1, 0, 1]
[1 0 1]
[3 1 1]
[ 3 -1  1]
[[ 2  4  4]
 [ 4 11  9]
 [ 4  9 11]]
[[ 2  4  4]
 [ 4 11  9]
 [ 4  9 11]]
[[ 36  88  88]
 [ 88 218 214]
 [ 88 214 218]]
[[ 6.75    -1.375   -1.375  ]
 [-1.375    0.40625  0.15625]
 [-1.375    0.15625  0.40625]]
[ 6 16 16]
[-3.5   0.75  0.75]
[ 1.  0. -2.]
4
